name: Run on release

on: 
  workflow_dispatch:
  push:
    tags:        
      - '*'

jobs:
  say_release:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Released on ${GITHUB_REF#refs/heads/}!"
